spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
server.port=8080

# Elasticsearch 连接配置
search.elasticsearch.host=127.0.0.1
search.elasticsearch.port=9200
search.elasticsearch.scheme=http

# 项目数据文件路径
search.data.jd-file-path=./data/jddata.json
search.data.question-file-path=./data/trainnew.json
search.data.answer-file-path=./data/answersnew.json
